import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import { BsSearch } from "react-icons/bs";
import DotLoader from "react-spinners/DotLoader";
import Weather from "../components/Weather";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.WEATEHR_API_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);

    axios.get(url).then((res) => {
      setWeather(res.data);
    });

    setCity("");
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className="serach_card" onSubmit={fetchWeather}>
        <h2 className="text-center text-white m-0 mb-2">
          Search for city weather
        </h2>
        <div className="search_wrapper">
          <input
            placeholder="Search city..."
            className="input"
            value={city}
            onChange={(e) => setCity(e.target.value)}
          />
          <button type="submit" className="btn">
            <BsSearch /> Search
          </button>
        </div>
      </form>

      {loading ? (
        <div className="spinner">
          <DotLoader color="#ffffff" loading={loading} size={80} />
        </div>
      ) : (
        weather.main && <Weather weather={weather} />
      )}

      <br />
      <br />
      <br />
    </div>
  );
}
